### ISSUE TITLE
Boolector incompatible

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/what4-solvers#19]
The version of boolector provided here does not work with Cryptol-2.12.

```
Cryptol> :s prover=boolector
Warning: boolector installation not found
Cryptol> :s prover=w4-boolector
:s prover=w4-boolector
Warning: solver interaction failed with w4-boolector
    fd:16: hFlush: resource vanished (Broken pipe)
```

**Comment by RyanGlScott** [comment]
This is almost certainly because `boolector-3.2.2` (the version shipped with `what4-solvers`) removed its `--smt2-model` flag, which is a flag that `what4` and `sbv` previously passed to `boolector` to determine if it was configured correctly. There have been issues opened on both [the `sbv` issue tracker](https://github.com/LeventErkok/sbv/issues/531) and [the `what4` issue tracker](https://github.com/GaloisInc/what4/issues/145) about this, both of which have been fixed upstream. The [`sbv` fix](https://github.com/LeventErkok/sbv/commit/dd7880c7d80fa817915c11685a86c7e24d9a69e2) is now available on Hackage in `sbv-8.15` or later, so if you use a nightly version of Cryptol, then setting `prover=sbv-boolector` will work. The [`what4` fix](https://github.com/GaloisInc/what4/pull/148) has not yet appeared in a Hackage release, however.

If you'd prefer, I could downgrade the version of `boolector` used in `what4-solvers` to 3.2.1. That version still has the `--smt2-model` flag and will therefore work with old versions of `what4` and `sbv`. Alternatively, one could wait until new versions of `what4` and `cryptol` have been released with the appropriate fix, although that will likely take a bit longer.

**Comment by weaversa** [comment]
Thanks @RyanGlScott! I'm happy to locally use the older boolector for a while. I'll watch here for when things should start working normally again.

**Comment by RyanGlScott** [comment]
After GaloisInc/cryptol#1346, the `master` branch of `cryptol` should now support `boolector-3.2.2`. We'll work on making a new Cryptol release with these changes in the coming month or so.
